//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator C:\Users\MIHO-D\source\repos\Bof.Stat.DCS\Bof.Stat.DCS.Converter\Schemas\MAPE_1.0.xsd -0 --namespace=Bof.Stat.DCS.Converter.Model.XML.MAPE --collectionSettersMode=Public --nullableReferenceAttributes -v --enumAsString
namespace Bof.Stat.DCS.Converter.Model.XML.MAPE
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("headerType", Namespace = "http://bof.fi/MAPE")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HeaderType
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("typeOfDataProviderIdentifier")]
        public string TypeOfDataProviderIdentifier { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum length: 10.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("dataProviderIdentifier")]
        public string DataProviderIdentifier { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("typeOfReporterIdentifier")]
        public string TypeOfReporterIdentifier { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum length: 10.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("reporterIdentifier")]
        public string ReporterIdentifier { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("surveyCode")]
        public string SurveyCode { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("reportingPeriodEnd", DataType = "date")]
        public System.DateTime ReportingPeriodEnd { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 1.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("frequency")]
        public string Frequency { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("creationDate", DataType = "dateTime")]
        public System.DateTime CreationDate { get; set; }

        /// <summary>
        /// <para xml:lang="en">Maximum length: 500.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(500)]
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("entitysComment")]
        public string EntitysComment { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("accoType", Namespace = "http://bof.fi/MAPE")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccoType
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("accountsDepositsAndOffices")]
        public string AccountsDepositsAndOffices { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("depositType")]
        public string DepositType { get; set; }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("assetsTransferableViaNetwork")]
        public bool AssetsTransferableViaNetworkValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the AssetsTransferableViaNetwork property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AssetsTransferableViaNetworkValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> AssetsTransferableViaNetwork
        {
            get
            {
                if (this.AssetsTransferableViaNetworkValueSpecified)
                {
                    return this.AssetsTransferableViaNetworkValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AssetsTransferableViaNetworkValue = value.GetValueOrDefault();
                this.AssetsTransferableViaNetworkValueSpecified = value.HasValue;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("eMoneyAccount")]
        public bool EMoneyAccountValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the EMoneyAccount property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool EMoneyAccountValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> EMoneyAccount
        {
            get
            {
                if (this.EMoneyAccountValueSpecified)
                {
                    return this.EMoneyAccountValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.EMoneyAccountValue = value.GetValueOrDefault();
                this.EMoneyAccountValueSpecified = value.HasValue;
            }
        }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("paymentServiceUser")]
        public string PaymentServiceUser { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("country")]
        public string Country { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-999999999999", "999999999999")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("amount")]
        public long AmountValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Amount property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AmountValueSpecified { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<long> Amount
        {
            get
            {
                if (this.AmountValueSpecified)
                {
                    return this.AmountValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AmountValue = value.GetValueOrDefault();
                this.AmountValueSpecified = value.HasValue;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999.99.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.99.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Total number of digits: 14.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-999999999999.99", "999999999999.99")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public decimal ValueValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Value property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ValueValueSpecified { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999.99.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.99.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Total number of digits: 14.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> Value
        {
            get
            {
                if (this.ValueValueSpecified)
                {
                    return this.ValueValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ValueValue = value.GetValueOrDefault();
                this.ValueValueSpecified = value.HasValue;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("cardType", Namespace = "http://bof.fi/MAPE")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CardType
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("cardType")]
        public string CardTypeProperty { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("eMoneyCardType")]
        public string EMoneyCardType { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("scheme")]
        public string Scheme { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("cashFunction")]
        public bool CashFunction { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("combinationCard")]
        public string CombinationCard { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("cardTechnology")]
        public string CardTechnology { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("paymentServiceUser")]
        public string PaymentServiceUser { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("country")]
        public string Country { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-999999999999", "999999999999")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("amount")]
        public long Amount { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("termType", Namespace = "http://bof.fi/MAPE")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TermType
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("terminalType")]
        public string TerminalType { get; set; }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("eftpos")]
        public bool EftposValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Eftpos property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool EftposValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> Eftpos
        {
            get
            {
                if (this.EftposValueSpecified)
                {
                    return this.EftposValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.EftposValue = value.GetValueOrDefault();
                this.EftposValueSpecified = value.HasValue;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("contactlessPayment")]
        public bool ContactlessPaymentValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ContactlessPayment property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ContactlessPaymentValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> ContactlessPayment
        {
            get
            {
                if (this.ContactlessPaymentValueSpecified)
                {
                    return this.ContactlessPaymentValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ContactlessPaymentValue = value.GetValueOrDefault();
                this.ContactlessPaymentValueSpecified = value.HasValue;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("terminalAcceptingEMoney")]
        public bool TerminalAcceptingEMoneyValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TerminalAcceptingEMoney property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TerminalAcceptingEMoneyValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> TerminalAcceptingEMoney
        {
            get
            {
                if (this.TerminalAcceptingEMoneyValueSpecified)
                {
                    return this.TerminalAcceptingEMoneyValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TerminalAcceptingEMoneyValue = value.GetValueOrDefault();
                this.TerminalAcceptingEMoneyValueSpecified = value.HasValue;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("eMoneyLoadingUnloading")]
        public bool EMoneyLoadingUnloadingValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the EMoneyLoadingUnloading property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool EMoneyLoadingUnloadingValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> EMoneyLoadingUnloading
        {
            get
            {
                if (this.EMoneyLoadingUnloadingValueSpecified)
                {
                    return this.EMoneyLoadingUnloadingValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.EMoneyLoadingUnloadingValue = value.GetValueOrDefault();
                this.EMoneyLoadingUnloadingValueSpecified = value.HasValue;
            }
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("country")]
        public string Country { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -9999999999.</para>
        /// <para xml:lang="en">Maximum inclusive value: 9999999999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-9999999999", "9999999999")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("amount")]
        public long Amount { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("hpayType", Namespace = "http://bof.fi/MAPE")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HpayType
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("reportersRole")]
        public string ReportersRole { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("informationType")]
        public string InformationType { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("paymentService")]
        public string PaymentService { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("paymentServiceUser")]
        public string PaymentServiceUser { get; set; }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("electronic")]
        public bool ElectronicValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Electronic property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ElectronicValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> Electronic
        {
            get
            {
                if (this.ElectronicValueSpecified)
                {
                    return this.ElectronicValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ElectronicValue = value.GetValueOrDefault();
                this.ElectronicValueSpecified = value.HasValue;
            }
        }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("paymentOrder")]
        public string PaymentOrder { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("channelForGivingConsent")]
        public string ChannelForGivingConsent { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("paymentScheme")]
        public string PaymentScheme { get; set; }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("instantPayment")]
        public bool InstantPaymentValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the InstantPayment property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool InstantPaymentValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> InstantPayment
        {
            get
            {
                if (this.InstantPaymentValueSpecified)
                {
                    return this.InstantPaymentValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.InstantPaymentValue = value.GetValueOrDefault();
                this.InstantPaymentValueSpecified = value.HasValue;
            }
        }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("cardType")]
        public string CardType { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("eMoneyType")]
        public string EMoneyType { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("remoteNonRemote")]
        public string RemoteNonRemote { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("contactlessTechnology")]
        public string ContactlessTechnology { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("terminal")]
        public string Terminal { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("initiationChannel")]
        public string InitiationChannel { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("mobilePaymentType")]
        public string MobilePaymentType { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("customerAuthentication")]
        public string CustomerAuthentication { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("reasonForNonSCA")]
        public string ReasonForNonSca { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("fraudType")]
        public string FraudType { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("liabilityBearer")]
        public string LiabilityBearer { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("counterpartysPSPLocation")]
        public string CounterpartysPspLocation { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("terminalLocation")]
        public string TerminalLocation { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("currency")]
        public string Currency { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-999999999999", "999999999999")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("amount")]
        public long AmountValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Amount property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AmountValueSpecified { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<long> Amount
        {
            get
            {
                if (this.AmountValueSpecified)
                {
                    return this.AmountValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AmountValue = value.GetValueOrDefault();
                this.AmountValueSpecified = value.HasValue;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999.99.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.99.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Total number of digits: 14.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-999999999999.99", "999999999999.99")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public decimal Value { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("qpayType", Namespace = "http://bof.fi/MAPE")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QpayType
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("reportersRole")]
        public string ReportersRole { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("informationType")]
        public string InformationType { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("paymentService")]
        public string PaymentService { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("paymentServiceUser")]
        public string PaymentServiceUser { get; set; }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("electronic")]
        public bool ElectronicValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Electronic property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ElectronicValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> Electronic
        {
            get
            {
                if (this.ElectronicValueSpecified)
                {
                    return this.ElectronicValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ElectronicValue = value.GetValueOrDefault();
                this.ElectronicValueSpecified = value.HasValue;
            }
        }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("remoteNonRemote")]
        public string RemoteNonRemote { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("counterpartysPSPLocation")]
        public string CounterpartysPspLocation { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("terminalLocation")]
        public string TerminalLocation { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum length: 4.</para>
        /// <para xml:lang="en">Maximum length: 4.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(4)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4)]
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("industry")]
        public string Industry { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-999999999999", "999999999999")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("amount")]
        public long Amount { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999.99.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.99.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Total number of digits: 14.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-999999999999.99", "999999999999.99")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public decimal Value { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("apayType", Namespace = "http://bof.fi/MAPE")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApayType
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("reportersRole")]
        public string ReportersRole { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("informationType")]
        public string InformationType { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("paymentService")]
        public string PaymentService { get; set; }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("electronic")]
        public bool ElectronicValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Electronic property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ElectronicValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> Electronic
        {
            get
            {
                if (this.ElectronicValueSpecified)
                {
                    return this.ElectronicValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ElectronicValue = value.GetValueOrDefault();
                this.ElectronicValueSpecified = value.HasValue;
            }
        }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("channelForGivingConsent")]
        public string ChannelForGivingConsent { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("cardType")]
        public string CardType { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("remoteNonRemote")]
        public string RemoteNonRemote { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("terminal")]
        public string Terminal { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("customerAuthentication")]
        public string CustomerAuthentication { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("reasonForNonSCA")]
        public string ReasonForNonSca { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("fraudType")]
        public string FraudType { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("liabilityBearer")]
        public string LiabilityBearer { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("counterpartysPSPLocation")]
        public string CounterpartysPspLocation { get; set; }

        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("terminalLocation")]
        public string TerminalLocation { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-999999999999", "999999999999")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("amount")]
        public long AmountValue { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Amount property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AmountValueSpecified { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<long> Amount
        {
            get
            {
                if (this.AmountValueSpecified)
                {
                    return this.AmountValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AmountValue = value.GetValueOrDefault();
                this.AmountValueSpecified = value.HasValue;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999.99.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.99.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Total number of digits: 14.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-999999999999.99", "999999999999.99")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public decimal Value { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("servType", Namespace = "http://bof.fi/MAPE")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServType
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("service")]
        public string Service { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-999999999999", "999999999999")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("amount")]
        public long Amount { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("mapeReport", Namespace = "http://bof.fi/MAPE", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("mapeReport", Namespace = "http://bof.fi/MAPE")]
    public partial class MapeReport
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("header")]
        public Bof.Stat.DCS.Converter.Model.XML.MAPE.HeaderType Header { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.AccoType> _accoRecords;

        [System.Xml.Serialization.XmlArrayAttribute("accoRecords")]
        [System.Xml.Serialization.XmlArrayItemAttribute("acco", Namespace = "http://bof.fi/MAPE")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.AccoType> AccoRecords
        {
            get
            {
                return _accoRecords;
            }
            set
            {
                _accoRecords = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AccoRecords collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccoRecordsSpecified
        {
            get
            {
                return ((this.AccoRecords != null)
                            && (this.AccoRecords.Count != 0));
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapeReport" /> class.</para>
        /// </summary>
        public MapeReport()
        {
            this._accoRecords = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.AccoType>();
            this._cardRecords = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.CardType>();
            this._termRecords = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.TermType>();
            this._hpayRecords = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.HpayType>();
            this._qpayRecords = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.QpayType>();
            this._apayRecords = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.ApayType>();
            this._servRecords = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.ServType>();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.CardType> _cardRecords;

        [System.Xml.Serialization.XmlArrayAttribute("cardRecords")]
        [System.Xml.Serialization.XmlArrayItemAttribute("card", Namespace = "http://bof.fi/MAPE")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.CardType> CardRecords
        {
            get
            {
                return _cardRecords;
            }
            set
            {
                _cardRecords = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CardRecords collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CardRecordsSpecified
        {
            get
            {
                return ((this.CardRecords != null)
                            && (this.CardRecords.Count != 0));
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.TermType> _termRecords;

        [System.Xml.Serialization.XmlArrayAttribute("termRecords")]
        [System.Xml.Serialization.XmlArrayItemAttribute("term", Namespace = "http://bof.fi/MAPE")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.TermType> TermRecords
        {
            get
            {
                return _termRecords;
            }
            set
            {
                _termRecords = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the TermRecords collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TermRecordsSpecified
        {
            get
            {
                return ((this.TermRecords != null)
                            && (this.TermRecords.Count != 0));
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.HpayType> _hpayRecords;

        [System.Xml.Serialization.XmlArrayAttribute("hpayRecords")]
        [System.Xml.Serialization.XmlArrayItemAttribute("hpay", Namespace = "http://bof.fi/MAPE")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.HpayType> HpayRecords
        {
            get
            {
                return _hpayRecords;
            }
            set
            {
                _hpayRecords = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the HpayRecords collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HpayRecordsSpecified
        {
            get
            {
                return ((this.HpayRecords != null)
                            && (this.HpayRecords.Count != 0));
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.QpayType> _qpayRecords;

        [System.Xml.Serialization.XmlArrayAttribute("qpayRecords")]
        [System.Xml.Serialization.XmlArrayItemAttribute("qpay", Namespace = "http://bof.fi/MAPE")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.QpayType> QpayRecords
        {
            get
            {
                return _qpayRecords;
            }
            set
            {
                _qpayRecords = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the QpayRecords collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QpayRecordsSpecified
        {
            get
            {
                return ((this.QpayRecords != null)
                            && (this.QpayRecords.Count != 0));
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.ApayType> _apayRecords;

        [System.Xml.Serialization.XmlArrayAttribute("apayRecords")]
        [System.Xml.Serialization.XmlArrayItemAttribute("apay", Namespace = "http://bof.fi/MAPE")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.ApayType> ApayRecords
        {
            get
            {
                return _apayRecords;
            }
            set
            {
                _apayRecords = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ApayRecords collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApayRecordsSpecified
        {
            get
            {
                return ((this.ApayRecords != null)
                            && (this.ApayRecords.Count != 0));
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.ServType> _servRecords;

        [System.Xml.Serialization.XmlArrayAttribute("servRecords")]
        [System.Xml.Serialization.XmlArrayItemAttribute("serv", Namespace = "http://bof.fi/MAPE")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.ServType> ServRecords
        {
            get
            {
                return _servRecords;
            }
            set
            {
                _servRecords = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ServRecords collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServRecordsSpecified
        {
            get
            {
                return ((this.ServRecords != null)
                            && (this.ServRecords.Count != 0));
            }
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("schemaVersion")]
        public string SchemaVersion { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapeReportAccoRecords", Namespace = "http://bof.fi/MAPE", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapeReportAccoRecords
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.AccoType> _acco;

        [System.Xml.Serialization.XmlElementAttribute("acco")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.AccoType> Acco
        {
            get
            {
                return _acco;
            }
            set
            {
                _acco = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Acco collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccoSpecified
        {
            get
            {
                return ((this.Acco != null)
                            && (this.Acco.Count != 0));
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapeReportAccoRecords" /> class.</para>
        /// </summary>
        public MapeReportAccoRecords()
        {
            this._acco = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.AccoType>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapeReportCardRecords", Namespace = "http://bof.fi/MAPE", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapeReportCardRecords
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.CardType> _card;

        [System.Xml.Serialization.XmlElementAttribute("card")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.CardType> Card
        {
            get
            {
                return _card;
            }
            set
            {
                _card = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Card collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CardSpecified
        {
            get
            {
                return ((this.Card != null)
                            && (this.Card.Count != 0));
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapeReportCardRecords" /> class.</para>
        /// </summary>
        public MapeReportCardRecords()
        {
            this._card = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.CardType>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapeReportTermRecords", Namespace = "http://bof.fi/MAPE", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapeReportTermRecords
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.TermType> _term;

        [System.Xml.Serialization.XmlElementAttribute("term")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.TermType> Term
        {
            get
            {
                return _term;
            }
            set
            {
                _term = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Term collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TermSpecified
        {
            get
            {
                return ((this.Term != null)
                            && (this.Term.Count != 0));
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapeReportTermRecords" /> class.</para>
        /// </summary>
        public MapeReportTermRecords()
        {
            this._term = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.TermType>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapeReportHpayRecords", Namespace = "http://bof.fi/MAPE", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapeReportHpayRecords
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.HpayType> _hpay;

        [System.Xml.Serialization.XmlElementAttribute("hpay")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.HpayType> Hpay
        {
            get
            {
                return _hpay;
            }
            set
            {
                _hpay = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Hpay collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HpaySpecified
        {
            get
            {
                return ((this.Hpay != null)
                            && (this.Hpay.Count != 0));
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapeReportHpayRecords" /> class.</para>
        /// </summary>
        public MapeReportHpayRecords()
        {
            this._hpay = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.HpayType>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapeReportQpayRecords", Namespace = "http://bof.fi/MAPE", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapeReportQpayRecords
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.QpayType> _qpay;

        [System.Xml.Serialization.XmlElementAttribute("qpay")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.QpayType> Qpay
        {
            get
            {
                return _qpay;
            }
            set
            {
                _qpay = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Qpay collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QpaySpecified
        {
            get
            {
                return ((this.Qpay != null)
                            && (this.Qpay.Count != 0));
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapeReportQpayRecords" /> class.</para>
        /// </summary>
        public MapeReportQpayRecords()
        {
            this._qpay = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.QpayType>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapeReportApayRecords", Namespace = "http://bof.fi/MAPE", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapeReportApayRecords
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.ApayType> _apay;

        [System.Xml.Serialization.XmlElementAttribute("apay")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.ApayType> Apay
        {
            get
            {
                return _apay;
            }
            set
            {
                _apay = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Apay collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApaySpecified
        {
            get
            {
                return ((this.Apay != null)
                            && (this.Apay.Count != 0));
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapeReportApayRecords" /> class.</para>
        /// </summary>
        public MapeReportApayRecords()
        {
            this._apay = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.ApayType>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapeReportServRecords", Namespace = "http://bof.fi/MAPE", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapeReportServRecords
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.ServType> _serv;

        [System.Xml.Serialization.XmlElementAttribute("serv")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.ServType> Serv
        {
            get
            {
                return _serv;
            }
            set
            {
                _serv = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Serv collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServSpecified
        {
            get
            {
                return ((this.Serv != null)
                            && (this.Serv.Count != 0));
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapeReportServRecords" /> class.</para>
        /// </summary>
        public MapeReportServRecords()
        {
            this._serv = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.MAPE.ServType>();
        }
    }
}
