//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator C:\Users\MIHO-D\source\repos\Bof.Stat.DCS\Bof.Stat.DCS.Converter\Schemas\TIHA_1.0.xsd -0 --namespace=Bof.Stat.DCS.Converter.Model.XML.TIHA --collectionSettersMode=Public --nullableReferenceAttributes -v --enumAsString
namespace Bof.Stat.DCS.Converter.Model.XML.TIHA
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("headerType", Namespace="http://bof.fi/TIHA")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HeaderType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("typeOfDataProviderIdentifier")]
        public string TypeOfDataProviderIdentifier { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 10.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("dataProviderIdentifier")]
        public string DataProviderIdentifier { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("typeOfReporterIdentifier")]
        public string TypeOfReporterIdentifier { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 10.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("reporterIdentifier")]
        public string ReporterIdentifier { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("surveyCode")]
        public string SurveyCode { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("reportingPeriodEnd", DataType="date")]
        public System.DateTime ReportingPeriodEnd { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("frequency")]
        public string Frequency { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("creationDate", DataType="dateTime")]
        public System.DateTime CreationDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 500.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(500)]
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("entitysComment")]
        public string EntitysComment { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("sbsType", Namespace="http://bof.fi/TIHA")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SbsType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("instrument")]
        public string Instrument { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(100)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("internalIdentificationCode")]
        public string InternalIdentificationCode { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 12.</para>
        /// <para xml:lang="en">Maximum length: 12.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(12)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(12)]
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("isinCode")]
        public string IsinCode { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("instrumentsName")]
        public string InstrumentsName { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999999999.999999.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999999999.999999.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// <para xml:lang="en">Total number of digits: 24.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-999999999999999999.999999", "999999999999999999.999999")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("numberOfInstruments")]
        public decimal NumberOfInstrumentsValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the NumberOfInstruments property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool NumberOfInstrumentsValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999999999.999999.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999999999.999999.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// <para xml:lang="en">Total number of digits: 24.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> NumberOfInstruments
        {
            get
            {
                if (this.NumberOfInstrumentsValueSpecified)
                {
                    return this.NumberOfInstrumentsValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.NumberOfInstrumentsValue = value.GetValueOrDefault();
                this.NumberOfInstrumentsValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999999999.99.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999999999.99.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Total number of digits: 20.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-999999999999999999.99", "999999999999999999.99")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("totalNominalValue")]
        public decimal TotalNominalValueValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TotalNominalValue property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TotalNominalValueValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999999999.99.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999999999.99.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Total number of digits: 20.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> TotalNominalValue
        {
            get
            {
                if (this.TotalNominalValueValueSpecified)
                {
                    return this.TotalNominalValueValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalNominalValueValue = value.GetValueOrDefault();
                this.TotalNominalValueValueSpecified = value.HasValue;
            }
        }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("nominalCurrency")]
        public string NominalCurrency { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999999999.99.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999999999.99.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Total number of digits: 20.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-999999999999999999.99", "999999999999999999.99")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("totalMarketValue")]
        public decimal TotalMarketValue { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("marketCurrency")]
        public string MarketCurrency { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999999999.99.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999999999.99.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Total number of digits: 20.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-999999999999999999.99", "999999999999999999.99")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("dividends")]
        public decimal DividendsValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Dividends property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DividendsValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999999999.99.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999999999.99.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Total number of digits: 20.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> Dividends
        {
            get
            {
                if (this.DividendsValueSpecified)
                {
                    return this.DividendsValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DividendsValue = value.GetValueOrDefault();
                this.DividendsValueSpecified = value.HasValue;
            }
        }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("dividendCurrency")]
        public string DividendCurrency { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("issueDate", DataType="date")]
        public System.DateTime IssueDateValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IssueDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IssueDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> IssueDate
        {
            get
            {
                if (this.IssueDateValueSpecified)
                {
                    return this.IssueDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IssueDateValue = value.GetValueOrDefault();
                this.IssueDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("maturityDate", DataType="date")]
        public System.DateTime MaturityDateValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MaturityDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool MaturityDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> MaturityDate
        {
            get
            {
                if (this.MaturityDateValueSpecified)
                {
                    return this.MaturityDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.MaturityDateValue = value.GetValueOrDefault();
                this.MaturityDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("nextCouponDate", DataType="date")]
        public System.DateTime NextCouponDateValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the NextCouponDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool NextCouponDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> NextCouponDate
        {
            get
            {
                if (this.NextCouponDateValueSpecified)
                {
                    return this.NextCouponDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.NextCouponDateValue = value.GetValueOrDefault();
                this.NextCouponDateValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999999999.9999.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999999999.9999.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 4.</para>
        /// <para xml:lang="en">Total number of digits: 22.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-999999999999999999.9999", "999999999999999999.9999")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("couponRate")]
        public decimal CouponRateValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CouponRate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CouponRateValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -999999999999999999.9999.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999999999999999999.9999.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 4.</para>
        /// <para xml:lang="en">Total number of digits: 22.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> CouponRate
        {
            get
            {
                if (this.CouponRateValueSpecified)
                {
                    return this.CouponRateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CouponRateValue = value.GetValueOrDefault();
                this.CouponRateValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -99.</para>
        /// <para xml:lang="en">Maximum inclusive value: 99.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "-99", "99")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("couponFrequency")]
        public sbyte CouponFrequencyValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CouponFrequency property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CouponFrequencyValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: -99.</para>
        /// <para xml:lang="en">Maximum inclusive value: 99.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<sbyte> CouponFrequency
        {
            get
            {
                if (this.CouponFrequencyValueSpecified)
                {
                    return this.CouponFrequencyValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CouponFrequencyValue = value.GetValueOrDefault();
                this.CouponFrequencyValueSpecified = value.HasValue;
            }
        }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("issuersSector")]
        public string IssuersSector { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("issuersHomeCountry")]
        public string IssuersHomeCountry { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("typeOfHoldersIdentifier")]
        public string TypeOfHoldersIdentifier { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("holdersIdentifier")]
        public string HoldersIdentifier { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(100)]
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("holdersName")]
        public string HoldersName { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("holdersSector")]
        public string HoldersSector { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("holdersHomeTaxationCountry")]
        public string HoldersHomeTaxationCountry { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tihaReport", Namespace="http://bof.fi/TIHA", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("tihaReport", Namespace="http://bof.fi/TIHA")]
    public partial class TihaReport
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("header")]
        public Bof.Stat.DCS.Converter.Model.XML.TIHA.HeaderType Header { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.TIHA.SbsType> _sbsRecords;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("sbsRecords")]
        [System.Xml.Serialization.XmlArrayItemAttribute("sbs", Namespace="http://bof.fi/TIHA")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.TIHA.SbsType> SbsRecords
        {
            get
            {
                return _sbsRecords;
            }
            set
            {
                _sbsRecords = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TihaReport" /> class.</para>
        /// </summary>
        public TihaReport()
        {
            this._sbsRecords = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.TIHA.SbsType>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("schemaVersion")]
        public string SchemaVersion { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TihaReportSbsRecords", Namespace="http://bof.fi/TIHA", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TihaReportSbsRecords
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.TIHA.SbsType> _sbs;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("sbs")]
        public System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.TIHA.SbsType> Sbs
        {
            get
            {
                return _sbs;
            }
            set
            {
                _sbs = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TihaReportSbsRecords" /> class.</para>
        /// </summary>
        public TihaReportSbsRecords()
        {
            this._sbs = new System.Collections.ObjectModel.Collection<Bof.Stat.DCS.Converter.Model.XML.TIHA.SbsType>();
        }
    }
}
